image: Visual Studio 2022

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet build -c Release

test_script:
  - cmd: dotnet test -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: 4IvPlHuyHuU9+daM8Ys4HafPAWUtRynOjwhmraCkjC912DEpDTFSOVb8IwqDLp45
    on:
      appveyor_repo_tag: true
